sudo: required
services:
  - docker

before_install:
  - docker build -t hakunamatata007/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true hakunamatata007/react-test npm test

after_success:
  - docker build -t hakunamatata007/multi-client ./client
  - docker build -t hakunamatata007/multi-nginx ./nginx
  - docker build -t hakunamatata007/multi-server ./server
  - docker build -t hakunamatata007/multi-worker ./worker
  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push hakunamatata007/multi-client
  - docker push hakunamatata007/multi-nginx
  - docker push hakunamatata007/multi-server
  - docker push hakunamatata007/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker
  env: Docker-env
  bucket_name: elasticbeanstalk-us-east-1-861561398399
  bucket_path: docker
  on:
    branch: master
  access_key_id:
    secure: 'AKIA4RGIPUR72MIDIVV6'
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
