sudo: required
services:
  - docker

before_install:
  - docker build -t hakunamatata007/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true hakunamatata007/react-test npm test
  - echo $AWS_ACCESS_KEY
  - echo $AWS_SECRET_KEY

after_success:
  - docker build -t hakunamatata007/multi-client ./client
  - docker build -t hakunamatata007/multi-nginx ./nginx
  - docker build -t hakunamatata007/multi-server ./server
  - docker build -t hakunamatata007/multi-worker ./worker
  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push hakunamatata007/multi-client
  - docker push hakunamatata007/multi-nginx
  - docker push hakunamatata007/multi-server
  - docker push hakunamatata007/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-1-861561398399
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
